spring.application.name=passdock-be
spring.application.name=passdock-be
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/passdock}
spring.datasource.username=${DATABASE_USERNAME:passdock}
spring.datasource.password=${DATABASE_PASSWORD:passdock}
spring.flyway.enabled=${FLYWAY_ENABLED:false}
management.endpoints.web.exposure.include=health,info,metrics,prometheus
